//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_BioWell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circumference
    {
        public System.DateTime Date { get; set; }
        public string Patient_Username { get; set; }
        public Nullable<double> Neck { get; set; }
        public Nullable<double> Wrist { get; set; }
        public Nullable<double> Hip { get; set; }
        public Nullable<double> Thigh { get; set; }
        public Nullable<double> Chest { get; set; }
        public Nullable<double> Arm { get; set; }
        public Nullable<double> Waist { get; set; }
        public Nullable<double> Calf { get; set; }
    }
}
