//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_BioWell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public string Doctor_Username { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string HASH { get; set; }
        public byte[] SALT { get; set; }
        public string Password { get; set; }
    }
}
